#!/usr/bin/env python3
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class HostedOnboardingTests(unittest.TestCase):
    def read_public(self, name):
        return (ROOT / "web" / "public" / name).read_text(encoding="utf-8")

    def read_text(self, *parts):
        return (ROOT.joinpath(*parts)).read_text(encoding="utf-8")

    def test_account_page_has_explicit_email_signup(self):
        html = self.read_public("account.html")
        js = self.read_public("account.js")
        self.assertIn('id="password-signup"', html)
        self.assertIn("Create account", html)
        self.assertIn("sb.auth.signUp", js)
        self.assertIn("emailRedirectTo: `${window.location.origin}/account.html`", js)
        self.assertIn('id="key-limit-note"', html)
        self.assertIn("maxActiveApiKeysPerCustomer", js)
        self.assertIn("Client setup", html)
        self.assertIn('id="client-openai-code"', html)
        self.assertIn('id="client-codex-code"', html)
        self.assertIn('id="client-anthropic-code"', html)
        self.assertIn("openaiSdkSetupText", js)
        self.assertIn("codexSetupText", js)
        self.assertIn("anthropicSetupText", js)
        self.assertIn("sage-router-hosted", js)
        self.assertIn('env_key = "OPENAI_API_KEY"', js)
        self.assertIn("[profiles.sage-router-frontier]", js)
        self.assertIn("sage-router/frontier", js)
        self.assertIn("sk_sage_your_key_here", js)
        self.assertIn("codex --profile sage-router-frontier", js)
        self.assertNotIn("sage-router-hosted.config.toml", js)
        self.assertNotIn("codex --profile sage-router-hosted", js)
        self.assertIn('id="step-verify"', html)
        self.assertIn('id="step-first-request"', html)
        self.assertIn('id="launch-next-action"', html)
        self.assertIn("generated-key to first routed request funnel", html)
        self.assertIn("keyVerifiedThisSession", js)
        self.assertIn("renderLaunchNextAction", js)
        self.assertIn("launch-verify-status", js)
        self.assertIn("launch-first-request-status", js)
        self.assertIn("usage?.requests", js)
        self.assertIn("test the key against /v1/models", js)
        self.assertIn("first sage-router/frontier chat completion", js)
        self.assertIn('id="preauth-plans"', html)
        self.assertIn('id="preauth-plan-summary"', html)
        self.assertIn('id="plan-preview-route-cost"', html)
        self.assertIn('data-preauth-plan', js)
        self.assertIn("function renderPreauthPlanPreview", js)
        self.assertIn("function costPerThousandRequests", js)
        self.assertIn("Sign in to continue to checkout", js)

    def test_readiness_checks_public_supabase_auth_settings(self):
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        readme = self.read_text("README.md")
        self.assertIn("discover_supabase_anon_key", readiness)
        self.assertIn("supabase_key_for_project", readiness)
        self.assertIn('SUPABASE_URL="${SAGE_ROUTER_SUPABASE_URL:-https://${SUPABASE_PROJECT_REF}.supabase.co}"', readiness)
        self.assertNotIn('PUBLIC_SUPABASE_URL:-https://${SUPABASE_PROJECT_REF}.supabase.co', readiness)
        self.assertIn("check_public_supabase_auth_settings", readiness)
        self.assertIn("/auth/v1/settings", readiness)
        self.assertIn("public Supabase auth settings expose browser-visible email/OAuth provider state", readiness)
        self.assertIn("Supabase GitHub provider mismatch", readiness)
        self.assertIn("public browser-visible Supabase auth settings", readme)
        self.assertIn("durable quotas", readiness)
        self.assertIn("anonymous model and analytics APIs are blocked with hosted onboarding guidance", readiness)
        self.assertIn("accountUrl", readiness)
        self.assertIn("apiKeyPrefix", readiness)
        self.assertIn("check_public_api_browser_boundary", readiness)
        self.assertIn("public API root and dashboard paths stay JSON-auth gated", readiness)
        self.assertIn("API-only browser/dashboard boundary", readme)

    def test_github_supabase_configurator_verifies_management_and_public_state(self):
        script = self.read_text("scripts", "configure_supabase_github_auth.sh")
        readme = self.read_text("README.md")
        self.assertIn("external_github_enabled: true", script)
        self.assertIn("Supabase GitHub auth verification failed", script)
        self.assertIn("Supabase public auth settings verification failed", script)
        self.assertIn("/auth/v1/settings", script)
        self.assertIn("discover_supabase_anon_key", script)
        self.assertIn("supabase_key_for_project", script)
        self.assertIn('SUPABASE_URL="${SAGE_ROUTER_SUPABASE_URL:-https://${PROJECT_REF}.supabase.co}"', script)
        self.assertNotIn("PUBLIC_SUPABASE_URL:-${VITE_SUPABASE_URL", script)
        self.assertIn("VITE_SUPABASE_PUBLISHABLE_KEY", script)
        self.assertIn("browser-visible OAuth buttons match the", readme)

    def test_github_app_bootstrap_opens_windows_temp_copy_from_wsl(self):
        script = self.read_text("scripts", "bootstrap_github_supabase_auth.sh")
        readme = self.read_text("README.md")
        callback = self.read_public("github-app-manifest.html")
        self.assertIn("win_temp", script)
        self.assertIn("sage-router-github-auth-app.html", script)
        self.assertIn("[Uri](\\$p)", script)
        self.assertIn("Start-Process '$windows_form_uri'", script)
        self.assertIn("SAGEROUTER_GITHUB_APP_MANIFEST_URL", script)
        self.assertIn("urllib.parse.urlparse", script)
        self.assertIn("parse_qs(parsed.query)", script)
        self.assertIn("bash scripts/bootstrap_github_supabase_auth.sh ${shellQuote(window.location.href)}", callback)
        self.assertIn('name="robots" content="noindex,nofollow"', callback)
        self.assertIn("short-lived GitHub manifest code", callback)
        self.assertIn("Code copied", callback)
        self.assertIn("SAGEROUTER_GITHUB_APP_LOCAL_CAPTURE=0 bash scripts/bootstrap_github_supabase_auth.sh", callback)
        self.assertIn("Timed out waiting for the GitHub manifest approval redirect. Retry with SAGEROUTER_GITHUB_APP_LOCAL_CAPTURE=0", script)
        self.assertIn("Windows temp directory", readme)
        self.assertIn("cannot read `\\\\wsl.localhost` or WSL `/tmp` paths", readme)
        self.assertIn("temporary one-hour `code`", readme)
        self.assertIn("noindex,nofollow", readme)
        self.assertIn("full callback URL or the raw code", readme)
        self.assertIn("https://app.sagerouter.dev/github-app-manifest.html?code=...", readme)

    def test_account_page_has_stripe_billing_management(self):
        html = self.read_public("account.html")
        js = self.read_public("account.js")
        self.assertIn('id="stripe-portal"', html)
        self.assertIn("Manage billing", html)
        self.assertIn("api('/billing/stripe/portal'", js)
        self.assertIn("params.get('billing')", js)
        self.assertIn("billing === 'portal'", js)

    def test_pricing_plan_links_preselect_checkout_plan(self):
        pricing = self.read_public("pricing.html")
        js = self.read_public("account.js")
        router = self.read_text("router.py")
        self.assertIn('/account.html?plan=lite', pricing)
        self.assertIn('/account.html?plan=pro', pricing)
        self.assertIn('/account.html?plan=max', pricing)
        self.assertIn("SELECTED_PLAN_STORAGE_KEY", js)
        self.assertIn("function requestedPlanFromUrl", js)
        self.assertIn("function applyRequestedPlanFromUrl", js)
        self.assertIn("rememberSelectedPlan(requested)", js)
        self.assertIn("renderPreauthPlanPreview(availablePlans)", js)
        self.assertIn("applyRequestedPlanFromUrl();", js)
        self.assertIn("Stripe checkout returned for ${planDisplay(selectedPlan)}", js)
        self.assertIn("Checkout cancelled. ${planDisplay(selectedPlan)} is still selected.", js)
        self.assertIn("JSON.stringify({ plan: selectedPlan })", js)
        self.assertIn("checkout=success&plan={urllib.parse.quote(plan", router)
        self.assertIn("checkout=cancel&plan={urllib.parse.quote(plan", router)

    def test_calculator_recommends_checkout_plan_before_signup(self):
        calculator = self.read_public("model-routing-calculator.html")
        readme = self.read_text("README.md")
        web_readme = self.read_text("web", "README.md")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")

        self.assertIn('id="recommendedPlan"', calculator)
        self.assertIn('id="recommendedPlanReason"', calculator)
        self.assertIn('id="startRecommendedPlan"', calculator)
        self.assertIn('id="createHostedKey"', calculator)
        self.assertIn("PLAN_LIMITS", calculator)
        self.assertIn("function recommendedPlanFor", calculator)
        self.assertIn("function planCheckoutUrl", calculator)
        self.assertIn("/account.html?plan=${encodeURIComponent(planKey)}", calculator)
        self.assertIn("Recommended hosted plan", calculator)
        self.assertIn("Recommended hosted plan: ${plan.label}", calculator)
        self.assertIn("Workflow text and prompt bodies stay in your browser.", calculator)
        self.assertIn("function trackFunnelEvent", calculator)
        self.assertIn("navigator.sendBeacon('/api/funnel-event'", calculator)
        self.assertIn("calculator_checkout_clicked", calculator)
        self.assertIn("calculator_audit_brief_copied", calculator)
        self.assertIn("calculator recommends", readme)
        self.assertIn("Lite/Pro/Max from workflow volume", readme)
        self.assertIn("that plan into `/account.html?plan=...`", readme)
        self.assertIn("recommends Lite/Pro/Max", web_readme)
        self.assertIn("preselected checkout", launch_plan)

    def test_landing_page_prioritizes_hosted_api_key_onboarding(self):
        landing = self.read_text("web", "src", "main.jsx")
        readme = self.read_text("README.md")
        web_readme = self.read_text("web", "README.md")

        self.assertIn("Hosted API live", landing)
        self.assertIn('href="/account.html?plan=pro"', landing)
        self.assertIn("Create hosted API key", landing)
        self.assertIn("Compare hosted plans", landing)
        self.assertIn("Read quickstart", landing)
        self.assertIn("https://api.sagerouter.dev/v1", landing)
        self.assertIn("Hosted plans include account-managed keys", landing)
        self.assertIn("Run locally", landing)
        self.assertIn("Hosted signup is live", landing)
        self.assertIn("future managed-provider beta interest", landing)
        self.assertIn("/managed-access", landing)
        self.assertIn("Managed access beta", landing)
        self.assertIn("interest === 'managed-access'", landing)
        self.assertIn('name="interest"', landing)
        self.assertIn("Requesting private-beta interest for managed provider access", landing)
        self.assertIn("Create hosted API key", readme)
        self.assertIn("homepage primary CTA", readme)
        self.assertIn("/managed-access", readme)
        self.assertIn("primary homepage CTA", web_readme)
        self.assertIn("waitlist remains secondary", web_readme)

    def test_codex_setup_page_is_discoverable_and_launch_gated(self):
        codex = self.read_public("docs/codex.html")
        quickstart = self.read_public("quickstart.html")
        models = self.read_public("models.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        readme = self.read_text("README.md")
        web_readme = self.read_text("web", "README.md")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")

        self.assertIn("Sage Router Codex Setup", codex)
        self.assertIn('base_url = "https://api.sagerouter.dev/v1/"', codex)
        self.assertIn('base_url = "http://127.0.0.1:8790/v1/"', codex)
        self.assertIn('base_url = "http://&lt;tailnet-host&gt;:8790/v1/"', codex)
        self.assertIn('wire_api = "responses"', codex)
        self.assertIn("sage-router/frontier", codex)
        self.assertIn("sk_sage_your_key_here", codex)
        self.assertIn("Do not paste prompts", codex)
        self.assertIn("codex --profile sage-router-frontier", codex)
        self.assertIn("codex --profile sage-router-local-frontier", codex)

        self.assertIn("/docs/codex", quickstart)
        self.assertIn("Read the dedicated Codex setup page", quickstart)
        self.assertIn("[profiles.sage-router-frontier]", quickstart)
        self.assertIn("/docs/codex", models)
        self.assertIn("local port <code>8790</code>", models)
        self.assertIn("https://sagerouter.dev/docs/codex", sitemap)
        self.assertIn("Codex setup: https://sagerouter.dev/docs/codex", llms)
        self.assertIn("Dedicated Codex setup lives at https://sagerouter.dev/docs/codex", llms)
        self.assertIn("Codex setup page: https://sagerouter.dev/docs/codex", llms_full)
        self.assertIn('base_url = "https://api.sagerouter.dev/v1/"', llms_full)
        self.assertIn("http://127.0.0.1:8790/v1/", llms_full)

        self.assertIn("check_marketing_codex_docs_page", readiness)
        self.assertIn("marketing Codex setup page is live in sitemap and LLM discovery", readiness)
        self.assertIn("/docs/codex", readme)
        self.assertIn("https://sagerouter.dev/docs/codex", readme)
        self.assertIn("local `http://127.0.0.1:8790/v1/`", readme)
        self.assertIn("Dedicated Codex setup page at `/docs/codex`", web_readme)
        self.assertIn("/docs/codex", launch_plan)
        self.assertIn("local port\n  `8790`", launch_plan)

    def test_account_page_shows_usage_and_quota(self):
        html = self.read_public("account.html")
        js = self.read_public("account.js")
        self.assertIn('id="usage-status"', html)
        self.assertIn('id="usage-fill"', html)
        self.assertIn('id="usage-remaining"', html)
        self.assertIn('id="usage-recommendation"', html)
        self.assertIn('id="usage-upgrade"', html)
        self.assertIn("api('/account/usage'", js)
        self.assertIn("rateLimitPerMinute", js)
        self.assertIn("renderUpgradeRecommendation", js)
        self.assertIn("Usage is above 90%", js)
        self.assertIn("Usage is above 75%", js)
        self.assertIn("Upgrade to", js)
        self.assertIn("recommendedUpgradePlan", js)
        self.assertIn("scrollIntoView", js)

    def test_login_page_has_explicit_email_signup(self):
        html = self.read_public("login.html")
        js = self.read_public("auth.js")
        self.assertIn('id="password-signup"', html)
        self.assertIn("Create account", html)
        self.assertIn("sb.auth.signUp", js)
        self.assertIn("emailRedirectTo: `${window.location.origin}/login.html`", js)

    def test_analytics_page_has_explicit_email_signup_and_account_link(self):
        html = self.read_public("analytics.html")
        js = self.read_public("analytics.js")
        readme = self.read_text("README.md")
        analytics_doc = self.read_text("docs", "ANALYTICS.md")
        self.assertIn('id="password-signup"', html)
        self.assertIn("Create account", html)
        self.assertIn('href="/account.html"', html)
        self.assertIn("Manage API access", html)
        self.assertIn('id="account-readiness"', html)
        self.assertIn('id="readiness-action"', html)
        self.assertIn('id="readiness-plan"', html)
        self.assertIn('id="readiness-routing"', html)
        self.assertIn('id="readiness-keys"', html)
        self.assertIn('id="readiness-usage"', html)
        self.assertIn("sb.auth.signUp", js)
        self.assertIn("emailRedirectTo: `${window.location.origin}/analytics.html`", js)
        self.assertIn("fetchAccountReadiness", js)
        self.assertIn("api(s, '/account/plan')", js)
        self.assertIn("api(s, '/account/usage')", js)
        self.assertIn("api(s, '/account/api-keys')", js)
        self.assertIn("renderAccountReadiness", js)
        self.assertIn("Quota is above 90%", js)
        self.assertIn("Choose a paid plan or finish checkout", js)
        self.assertIn("plan, usage, generated-key", readme)
        self.assertIn("Account readiness", analytics_doc)

    def test_operator_launch_funnel_page_uses_private_token_boundary(self):
        html = self.read_public("launch-funnel.html")
        js = self.read_public("launch-funnel.js")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        readme = self.read_text("README.md")
        analytics_doc = self.read_text("docs", "ANALYTICS.md")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")

        self.assertIn("Sage Router Launch Funnel", html)
        self.assertIn("Private operator dashboard", html)
        self.assertIn('name="robots" content="noindex,nofollow"', html)
        self.assertIn("SAGE_ROUTER_API_KEY or analytics token", html)
        self.assertIn('id="remember-token"', html)
        self.assertIn('id="kpi-marketing-intent"', html)
        self.assertIn('id="kpi-managed-access"', html)
        self.assertIn('id="metric-marketing-intent"', html)
        self.assertIn('id="metric-managed-share"', html)
        self.assertIn('id="plan-mix"', html)
        self.assertIn("https://api.sagerouter.dev", js)
        self.assertIn("/analytics/funnel?days=", js)
        self.assertIn("sessionStorage", js)
        self.assertIn("marketingIntentEvents", js)
        self.assertIn("managedAccessBetaInterest", js)
        self.assertIn("managedAccessShareOfWaitlist", js)
        self.assertIn("containsEmails === false", js)
        self.assertIn("launch-funnel.html", readiness)
        self.assertIn("operator launch funnel CORS preflights are enabled", readiness)
        self.assertIn("managedAccessBetaInterest", readiness)
        self.assertIn("managedAccessShareOfWaitlist", readiness)
        self.assertIn("https://app.sagerouter.dev/launch-funnel.html", readme)
        self.assertIn("tab-scoped `sessionStorage`", readme)
        self.assertIn("hosted operator dashboard", analytics_doc)
        self.assertIn("private admin/analytics token", launch_plan)

    def test_public_status_page_uses_edge_health_and_pricing(self):
        html = self.read_public("status.html")
        js = self.read_public("status.js")
        self.assertIn("Public edge status", html)
        self.assertIn('id="upstreams"', html)
        self.assertIn('id="plans"', html)
        self.assertIn('id="controls"', html)
        self.assertIn('id="resilience-summary"', html)
        self.assertIn("CDN-style reliability evidence", html)
        self.assertIn('id="reliability-evidence"', html)
        self.assertIn('id="reliability-summary"', html)
        self.assertIn("/edge/health", js)
        self.assertIn("/pricing", js)
        self.assertIn("renderReliabilityEvidence", js)
        self.assertIn("originKind", js)
        self.assertIn("cloud fallback", js)
        self.assertIn("Tailnet", js)
        self.assertIn("Hybrid failover is active", js)
        self.assertIn("controlPlane", js)
        self.assertIn("enforcement", js)
        self.assertIn("rateLimitEnabled", js)
        self.assertIn("quotaEnabled", js)
        self.assertIn("apiKeyAuthCacheSeconds", js)
        self.assertIn("apiKeyPrefix", js)
        self.assertIn("lowest-latency healthy route", js)
        self.assertIn("https://api.sagerouter.dev", js)
        self.assertIn("api.sagerouter.dev/v1", html)
        readme = self.read_text("README.md")
        self.assertIn("CDN-style reliability evidence", readme)
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        self.assertIn("CDN-style reliability evidence", readiness)
        self.assertIn("hosted login, account, API-key verification, analytics, operator launch funnel, reliability status, and GitHub auth callback pages are live", readiness)

    def test_security_doc_distinguishes_private_router_from_hosted_public_edge(self):
        security = self.read_text("SECURITY.md")
        normalized = " ".join(security.split())
        self.assertIn("Hosted public edge", security)
        self.assertIn("https://api.sagerouter.dev", security)
        self.assertIn("/v1/*", security)
        self.assertIn("/v1beta/*", security)
        self.assertIn("active generated `sk_sage_*`", security)
        self.assertIn("account and billing UI routes require a valid Supabase user JWT", security)
        self.assertIn("`/analytics` and `/analytics/funnel` are operator-only routes", security)
        self.assertIn("Customer dashboards use `/account/analytics`", security)
        self.assertIn("anonymous model and analytics APIs are blocked", normalized)
        self.assertIn("generated API-key revocation is effective on the next request", normalized)
        self.assertNotIn("The `/health`, `/v1/models`, and analytics endpoints are anonymous.", security)

    def test_public_security_page_is_discoverable_and_matches_hosted_edge_boundary(self):
        page = self.read_public("security.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        landing = self.read_text("web", "src", "main.jsx")
        web_readme = self.read_text("web", "README.md")
        readme = self.read_text("README.md")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")

        self.assertIn("Sage Router Security", page)
        self.assertIn("hosted public API edge", page)
        self.assertIn("Anonymous model and analytics requests fail closed", page)
        self.assertIn("active generated <code>sk_sage_*</code>", page)
        self.assertIn("valid Supabase user JWT", page)
        self.assertIn("/analytics/funnel", page)
        self.assertIn("privacy-safe operational telemetry", page)
        self.assertIn("Managed provider access is not active in public plans", page)
        self.assertIn("https://sagerouter.dev/security", sitemap)
        self.assertIn("Security: https://sagerouter.dev/security", llms)
        self.assertIn("Hosted security requires generated `sk_sage_*`", llms)
        self.assertIn("The hosted public edge is API-only", llms_full)
        self.assertIn("/security", landing)
        self.assertIn("Review security", landing)
        self.assertIn("marketing security, support, terms, privacy, and acceptable-use pages are live and in sitemap", readiness)
        self.assertIn("public `/security` trust page", web_readme)
        self.assertIn("public security/trust", readme)
        self.assertIn("`/security`", launch_plan)

    def test_public_support_page_is_discoverable_and_secret_safe(self):
        page = self.read_public("support.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        pricing = self.read_public("pricing.html")
        status = self.read_public("status.html")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        readme = self.read_text("README.md")
        web_readme = self.read_text("web", "README.md")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")

        self.assertIn("Sage Router Support", page)
        self.assertIn("Do Not Send Secrets", page)
        self.assertIn("Account and Billing", page)
        self.assertIn("Quota and API Keys", page)
        self.assertIn("Reliability and 503s", page)
        self.assertIn("Security and Abuse", page)
        self.assertIn("Stripe billing portal", page)
        self.assertIn("manual or crypto settlement", page)
        self.assertIn("prompts, workflow text, provider credentials, OAuth tokens", page)
        self.assertIn("generated API keys, private keys, session cookies", page)
        self.assertIn("/account.html", page)
        self.assertIn("/quickstart", page)
        self.assertIn("/status", page)
        self.assertIn("https://github.com/earlvanze/sage-router/issues", page)
        self.assertIn("https://sagerouter.dev/support", sitemap)
        self.assertIn("Support: https://sagerouter.dev/support", llms)
        self.assertIn("Hosted support covers account, billing, quota", llms)
        self.assertIn("Hosted support for account, billing, quota", llms_full)
        self.assertIn("/support", pricing)
        self.assertIn("/support", status)
        self.assertIn("check_legal_pages", readiness)
        self.assertIn("missing-no-secrets-boundary", readiness)
        self.assertIn("marketing security, support, terms, privacy, and acceptable-use pages are live and in sitemap", readiness)
        self.assertIn("public security/trust/support", readme)
        self.assertIn("support page gives those same customers", readme)
        self.assertIn("public `/support` page", web_readme)
        self.assertIn("Keep `/support` as the safe escalation path", launch_plan)

    def test_waitlist_endpoint_has_non_mutating_launch_health_check(self):
        function_js = self.read_text("web", "functions", "api", "waitlist.js")
        landing = self.read_text("web", "src", "main.jsx")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        readme = self.read_text("web", "README.md")
        deploy = self.read_text("web", "DEPLOY.md")
        self.assertIn("export async function onRequestGet", function_js)
        self.assertIn("sage-router-waitlist", function_js)
        self.assertIn("primaryTable: 'sage_router_waitlist'", function_js)
        self.assertIn("fallbackTable: 'funnel_leads'", function_js)
        self.assertIn("SAGEROUTER_TURNSTILE_SECRET_KEY", function_js)
        self.assertIn("SAGEROUTER_TURNSTILE_SITE_KEY", function_js)
        self.assertIn("https://challenges.cloudflare.com/turnstile/v0/siteverify", function_js)
        self.assertIn("turnstile_required", function_js)
        self.assertIn("turnstileReady", function_js)
        self.assertIn("allowedQualificationBuckets", function_js)
        self.assertIn("deployment: ['hosted-edge', 'tailnet-private', 'hybrid', 'unsure']", function_js)
        self.assertIn("providerAccess: ['byok', 'local-ollama', 'enterprise-contracts', 'needs-managed-access']", function_js)
        self.assertIn("sanitizeChoice", function_js)
        self.assertIn("monthly_volume: monthlyVolume", function_js)
        self.assertIn("sanitizedUrl", function_js)
        self.assertIn("payload.interest", function_js)
        self.assertIn("metadata = {", function_js)
        self.assertIn("interest,", function_js)
        self.assertIn("deployment,", function_js)
        self.assertIn("provider_access: providerAccess", function_js)
        self.assertIn("sourcePage", function_js)
        self.assertIn("loadTurnstileScript", landing)
        self.assertIn("turnstileToken", landing)
        self.assertIn("new URLSearchParams(window.location.search)", landing)
        self.assertIn("managed-access", landing)
        self.assertIn("Complete verification first.", landing)
        self.assertIn("<WaitlistForm />", landing)
        self.assertIn("/api/waitlist", readiness)
        self.assertIn("turnstileRequired", readiness)
        self.assertIn("turnstileSiteKey", readiness)
        self.assertIn("hosted waitlist endpoint is configured", readiness)
        self.assertIn("GET /api/waitlist", readme)
        self.assertIn("SAGEROUTER_TURNSTILE_SECRET_KEY", deploy)
        self.assertIn("SAGEROUTER_TURNSTILE_SITE_KEY", deploy)

    def test_funnel_event_endpoint_tracks_pre_signup_cta_intent_privately(self):
        function_js = self.read_text("web", "functions", "api", "funnel-event.js")
        calculator = self.read_public("model-routing-calculator.html")
        pricing = self.read_public("pricing.html")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        migration = self.read_text("supabase", "migrations", "20260619053000_sage_router_funnel_events.sql")
        router = self.read_text("router.py")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")

        self.assertIn("sage-router-funnel-event", function_js)
        self.assertIn("sage_router_funnel_events", function_js)
        self.assertIn("ALLOWED_EVENTS", function_js)
        self.assertIn("calculator_checkout_clicked", function_js)
        self.assertIn("pricing_checkout_clicked", function_js)
        self.assertIn("containsEmails: false", function_js)
        self.assertIn("promptsStored: false", function_js)
        self.assertIn("ALLOWED_METADATA_KEYS", function_js)
        self.assertIn("source_page", function_js)
        self.assertIn("target", function_js)
        self.assertIn("sendBeacon('/api/funnel-event'", calculator)
        self.assertIn("trackPricingFunnelEvent", pricing)
        self.assertIn("pricing_checkout_clicked", pricing)
        self.assertIn("check_funnel_event_endpoint", readiness)
        self.assertIn("privacy-safe marketing funnel event endpoint is configured", readiness)
        self.assertIn("sage_router_funnel_events?select=id&limit=1", readiness)
        self.assertIn("marketingIntentEvents", router)
        self.assertIn("read_launch_marketing_funnel_counts", router)
        self.assertIn("marketingIntent", router)
        self.assertIn("create table if not exists public.sage_router_funnel_events", migration)
        self.assertIn("service role manages sage router funnel events", migration)
        self.assertIn("pre-signup CTA intent", launch_plan)

    def test_openrouter_comparison_page_is_discoverable(self):
        page = self.read_text("web", "public", "compare", "openrouter.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        landing = self.read_text("web", "src", "main.jsx")
        self.assertIn("Sage Router vs OpenRouter", page)
        self.assertIn('href="https://sagerouter.dev/compare/openrouter"', page)
        self.assertIn("Create hosted API key", page)
        self.assertIn("Bring your own authorized provider access", landing)
        self.assertIn("/compare/openrouter", landing)
        self.assertIn("https://sagerouter.dev/compare/openrouter", sitemap)
        self.assertIn("OpenRouter comparison: https://sagerouter.dev/compare/openrouter", llms)
        self.assertIn("OpenRouter alternative for agents", llms_full)
        self.assertIn("Managed-access beta", page)
        self.assertIn("/managed-access", page)
        self.assertIn("Request private-beta review", page)
        self.assertIn("SAGEROUTER_MARKETING_BASE_URL", readiness)
        self.assertIn("marketing OpenRouter comparison page is live and in sitemap", readiness)

    def test_managed_access_private_beta_page_is_discoverable_and_privacy_safe(self):
        page = self.read_public("managed-access.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        pricing = self.read_public("pricing.html")
        landing = self.read_text("web", "src", "main.jsx")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        readme = self.read_text("README.md")
        web_readme = self.read_text("web", "README.md")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")

        self.assertIn("Sage Router Managed Access Private Beta", page)
        self.assertIn('href="https://sagerouter.dev/managed-access"', page)
        self.assertIn('name="interest" type="hidden" value="managed-access"', page)
        self.assertIn("fetch('/api/waitlist'", page)
        self.assertIn("Deployment preference", page)
        self.assertIn("Expected monthly routed requests", page)
        self.assertIn("Provider access posture", page)
        self.assertIn("needs-managed-access", page)
        self.assertIn("Do not submit prompts", page)
        self.assertIn("provider credentials, OAuth tokens", page)
        self.assertIn("generated API keys, private keys", page)
        self.assertIn("contact and small qualification buckets", page)
        self.assertIn("not active in public plans", page)
        self.assertIn("/account.html?plan=max", page)
        self.assertIn("https://sagerouter.dev/managed-access", sitemap)
        self.assertIn("Managed-access private beta: https://sagerouter.dev/managed-access", llms)
        self.assertIn("allowlisted qualification buckets only", llms)
        self.assertIn("Managed-access private beta intake: https://sagerouter.dev/managed-access", llms_full)
        self.assertIn("/managed-access", pricing)
        self.assertIn("Request managed-access beta", pricing)
        self.assertIn("/managed-access", landing)
        self.assertIn("check_marketing_managed_access_page", readiness)
        self.assertIn("marketing managed-access private beta intake page is live in sitemap and LLM discovery", readiness)
        self.assertIn("managed-provider-access private beta intake page", readme)
        self.assertIn("Dedicated managed-access private beta intake", web_readme)
        self.assertIn("`/managed-access`", launch_plan)

    def test_hosted_pricing_page_and_10k_mrr_plan_are_discoverable(self):
        page = self.read_public("pricing.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")
        landing = self.read_text("web", "src", "main.jsx")
        readme = self.read_text("README.md")

        self.assertIn("Sage Router Hosted Pricing", page)
        self.assertIn("100 Lite, 200 Pro, and 50 Max customers is $10,200 MRR", page)
        self.assertIn("It does not grant unauthorized model access", page)
        self.assertIn("Managed provider access is not active in the public plans yet", page)
        self.assertIn("managedProviderAccess", page)
        self.assertIn("Request managed-access beta", page)
        self.assertIn("/managed-access", page)
        self.assertIn("Beta interest is demand capture only", page)
        self.assertIn("/provider-resale-terms", page)
        self.assertIn("/margin-policy", page)
        self.assertIn("https://sagerouter.dev/pricing", sitemap)
        self.assertIn("Hosted pricing: https://sagerouter.dev/pricing", llms)
        self.assertIn("Managed provider access is not active in public plans", llms)
        self.assertIn("balanced path to $10k MRR", llms_full)
        self.assertIn("publicLaunch.managedProviderAccess", llms_full)
        self.assertIn("Managed-access beta interest: https://sagerouter.dev/managed-access", llms)
        self.assertIn("captures contact and allowlisted qualification buckets only", llms_full)
        self.assertIn("/pricing", landing)
        self.assertIn("endpoint, limit, and launch metadata", readiness)
        self.assertIn("check_managed_provider_access_guard", readiness)
        self.assertIn("managed provider access remains disabled until provider resale terms", readiness)
        self.assertIn("SAGEROUTER_MANAGED_PROVIDER_RESALE_ENABLED", readiness)
        self.assertIn("marketing hosted pricing page is live and in sitemap", readiness)
        self.assertIn("Target: `$10,000 MRR`", launch_plan)
        self.assertIn("publicLaunch.managedProviderAccess", launch_plan)
        self.assertIn("`/managed-access`", launch_plan)
        self.assertIn("waitlist `interest` metadata", launch_plan)
        self.assertIn("margin-policy URLs", launch_plan)
        self.assertIn("docs/saas-launch-10k-mrr.md", readme)
        self.assertIn("managed provider access guard", readme)

    def test_public_model_catalog_is_discoverable_without_opening_v1_models(self):
        page = self.read_public("models.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")
        security = self.read_text("SECURITY.md")
        readme = self.read_text("README.md")

        self.assertIn("Sage Router Model Catalog", page)
        self.assertIn("sage-router/frontier", page)
        self.assertIn("OpenAI and Codex-compatible", page)
        self.assertIn("Ollama and Ollama Cloud", page)
        self.assertIn("Live <code>/v1/models</code>", page)
        self.assertIn("require an active generated <code>sk_sage_*</code> key", page)
        self.assertIn("https://api.sagerouter.dev/model-catalog", page)
        self.assertIn("https://sagerouter.dev/models", sitemap)
        self.assertIn("Model catalog: https://sagerouter.dev/models", llms)
        self.assertIn("https://api.sagerouter.dev/model-catalog", llms)
        self.assertIn("OpenRouter-style model discovery", llms_full)
        self.assertIn("Live `https://api.sagerouter.dev/v1/models`", llms_full)
        self.assertIn("check_public_model_catalog", readiness)
        self.assertIn("marketing model catalog page is live in sitemap and LLM discovery", readiness)
        self.assertIn("/model-catalog", launch_plan)
        self.assertIn("/model-catalog", security)
        self.assertIn("/model-catalog", readme)

    def test_public_quickstart_onboards_openai_compatible_clients(self):
        page = self.read_public("quickstart.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")
        landing = self.read_text("web", "src", "main.jsx")
        readme = self.read_text("README.md")
        web_readme = self.read_text("web", "README.md")

        self.assertIn("Sage Router API Quickstart", page)
        self.assertIn("OPENAI_BASE_URL=https://api.sagerouter.dev/v1", page)
        self.assertIn("OPENAI_API_KEY=sk_sage_your_key_here", page)
        self.assertIn("curl https://api.sagerouter.dev/v1/chat/completions", page)
        self.assertIn("sage-router/frontier", page)
        self.assertIn("Live <code>/v1/models</code> requires an active generated <code>sk_sage_*</code> key", page)
        self.assertIn("JavaScript", page)
        self.assertIn("Python", page)
        self.assertIn("Codex", page)
        self.assertIn("[model_providers.sage-router-hosted]", page)
        self.assertIn("[profiles.sage-router-frontier]", page)
        self.assertIn('env_key = "OPENAI_API_KEY"', page)
        self.assertIn("Read the dedicated Codex setup page", page)
        self.assertIn("codex --profile sage-router-frontier", page)
        self.assertIn("401", page)
        self.assertIn("402", page)
        self.assertIn("429", page)
        self.assertIn("503", page)
        self.assertIn("does not grant unauthorized model access", page)
        self.assertIn("https://sagerouter.dev/quickstart", sitemap)
        self.assertIn("API quickstart: https://sagerouter.dev/quickstart", llms)
        self.assertIn("The public API quickstart", llms_full)
        self.assertIn("/quickstart", landing)
        self.assertIn("Read quickstart", landing)
        self.assertIn("check_marketing_quickstart_page", readiness)
        self.assertIn("marketing API quickstart is live in sitemap and LLM discovery", readiness)
        self.assertIn("/quickstart", launch_plan)
        self.assertIn("https://sagerouter.dev/quickstart", readme)
        self.assertIn("Dedicated API quickstart page at `/quickstart`", web_readme)

    def test_acceptable_use_covers_managed_provider_access(self):
        page = self.read_public("acceptable-use.html")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")

        self.assertIn("Managed Provider Access", page)
        self.assertIn("provider access Sage Router is authorized to sell or operate", page)
        self.assertIn("managed-access acceptable-use boundary", readiness)

    def test_managed_provider_prerequisite_pages_are_discoverable(self):
        provider_page = self.read_public("provider-resale-terms.html")
        margin_page = self.read_public("margin-policy.html")
        pricing_page = self.read_public("pricing.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")
        readme = self.read_text("README.md")

        self.assertIn("Sage Router Provider Resale Terms", provider_page)
        self.assertIn("authorized to resell or operate", provider_page)
        self.assertIn("does not authorize pooled accounts", provider_page)
        self.assertIn("Managed provider access is not active", provider_page)
        self.assertIn("Sage Router Managed Access Margin Policy", margin_page)
        self.assertIn("positive unit economics", margin_page)
        self.assertIn("not unlimited unmetered resale", margin_page)
        self.assertIn("/provider-resale-terms", pricing_page)
        self.assertIn("/margin-policy", pricing_page)
        self.assertIn("https://sagerouter.dev/provider-resale-terms", sitemap)
        self.assertIn("https://sagerouter.dev/margin-policy", sitemap)
        self.assertIn("Provider Resale Terms: https://sagerouter.dev/provider-resale-terms", llms)
        self.assertIn("Managed Access Margin Policy: https://sagerouter.dev/margin-policy", llms)
        self.assertIn("publishing those pages does not activate managed resale", llms_full)
        self.assertIn("check_managed_provider_prerequisite_pages", readiness)
        self.assertIn("marketing provider resale terms and margin policy pages are live and in sitemap", readiness)
        self.assertIn("/provider-resale-terms", launch_plan)
        self.assertIn("/margin-policy", launch_plan)
        self.assertIn("provider-resale terms and margin-policy prerequisite pages", readme)

    def test_public_deploy_helper_pins_pages_production_and_cloud_run_digest(self):
        script = self.read_text("scripts", "deploy_sagerouter_public.sh")
        readme = self.read_text("README.md")
        deploy = self.read_text("web", "DEPLOY.md")
        gcp = self.read_text("deploy", "gcp", "README.md")

        self.assertIn("SAGEROUTER_CLOUDFLARE_PAGES_PRODUCTION_BRANCH:-main", script)
        self.assertIn("mktemp -d /tmp/sage-router-web", script)
        self.assertIn("--exclude='./node_modules'", script)
        self.assertIn("pages functions build functions", script)
        self.assertIn("--outdir dist/_worker.js", script)
        self.assertIn("--output-routes-path dist/_routes.json", script)
        self.assertIn("pages deploy \"$tmp/dist\"", script)
        self.assertIn("npx wrangler \"${wrangler_args[@]}\"", script)
        self.assertIn("--branch \"$PAGES_PRODUCTION_BRANCH\"", script)
        self.assertIn("GHCR_IMAGE_DIGEST", script)
        self.assertIn("containerimage.digest", script)
        self.assertIn("check_sagerouter_launch_readiness.sh", script)
        self.assertIn("deploys project `sage-router-web` to production branch `main`", readme)
        self.assertIn("`master` branch with Wrangler creates a preview deployment only", deploy)
        self.assertIn("resolves the latest successful GitHub Actions `Release image` digest", gcp)


if __name__ == "__main__":
    unittest.main()
