#!/usr/bin/env python3
from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]


class HostedOnboardingTests(unittest.TestCase):
    def read_public(self, name):
        return (ROOT / "web" / "public" / name).read_text(encoding="utf-8")

    def read_text(self, *parts):
        return (ROOT.joinpath(*parts)).read_text(encoding="utf-8")

    def test_account_page_has_explicit_email_signup(self):
        html = self.read_public("account.html")
        js = self.read_public("account.js")
        self.assertIn('id="password-signup"', html)
        self.assertIn("Create account", html)
        self.assertIn("sb.auth.signUp", js)
        self.assertIn("emailRedirectTo: `${window.location.origin}/account.html`", js)
        self.assertIn('id="key-limit-note"', html)
        self.assertIn("maxActiveApiKeysPerCustomer", js)

    def test_readiness_checks_public_supabase_auth_settings(self):
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        readme = self.read_text("README.md")
        self.assertIn("discover_supabase_anon_key", readiness)
        self.assertIn("check_public_supabase_auth_settings", readiness)
        self.assertIn("/auth/v1/settings", readiness)
        self.assertIn("public Supabase auth settings expose browser-visible email/OAuth provider state", readiness)
        self.assertIn("Supabase GitHub provider mismatch", readiness)
        self.assertIn("public browser-visible Supabase auth settings", readme)
        self.assertIn("durable quotas", readiness)
        self.assertIn("anonymous model and analytics APIs are blocked with hosted onboarding guidance", readiness)
        self.assertIn("accountUrl", readiness)
        self.assertIn("apiKeyPrefix", readiness)
        self.assertIn("check_public_api_browser_boundary", readiness)
        self.assertIn("public API root and dashboard paths stay JSON-auth gated", readiness)
        self.assertIn("API-only browser/dashboard boundary", readme)

    def test_github_supabase_configurator_verifies_management_and_public_state(self):
        script = self.read_text("scripts", "configure_supabase_github_auth.sh")
        readme = self.read_text("README.md")
        self.assertIn("external_github_enabled: true", script)
        self.assertIn("Supabase GitHub auth verification failed", script)
        self.assertIn("Supabase public auth settings verification failed", script)
        self.assertIn("/auth/v1/settings", script)
        self.assertIn("VITE_SUPABASE_PUBLISHABLE_KEY", script)
        self.assertIn("browser-visible OAuth buttons match the", readme)

    def test_github_app_bootstrap_opens_windows_temp_copy_from_wsl(self):
        script = self.read_text("scripts", "bootstrap_github_supabase_auth.sh")
        readme = self.read_text("README.md")
        self.assertIn("win_temp", script)
        self.assertIn("sage-router-github-auth-app.html", script)
        self.assertIn("[Uri](\\$p)", script)
        self.assertIn("Start-Process '$windows_form_uri'", script)
        self.assertIn("Windows temp directory", readme)
        self.assertIn("cannot read `\\\\wsl.localhost` or WSL `/tmp` paths", readme)

    def test_account_page_has_stripe_billing_management(self):
        html = self.read_public("account.html")
        js = self.read_public("account.js")
        self.assertIn('id="stripe-portal"', html)
        self.assertIn("Manage billing", html)
        self.assertIn("api('/billing/stripe/portal'", js)
        self.assertIn("params.get('billing')", js)
        self.assertIn("billing === 'portal'", js)

    def test_account_page_shows_usage_and_quota(self):
        html = self.read_public("account.html")
        js = self.read_public("account.js")
        self.assertIn('id="usage-status"', html)
        self.assertIn('id="usage-fill"', html)
        self.assertIn('id="usage-remaining"', html)
        self.assertIn("api('/account/usage'", js)
        self.assertIn("rateLimitPerMinute", js)

    def test_login_page_has_explicit_email_signup(self):
        html = self.read_public("login.html")
        js = self.read_public("auth.js")
        self.assertIn('id="password-signup"', html)
        self.assertIn("Create account", html)
        self.assertIn("sb.auth.signUp", js)
        self.assertIn("emailRedirectTo: `${window.location.origin}/login.html`", js)

    def test_analytics_page_has_explicit_email_signup_and_account_link(self):
        html = self.read_public("analytics.html")
        js = self.read_public("analytics.js")
        self.assertIn('id="password-signup"', html)
        self.assertIn("Create account", html)
        self.assertIn('href="/account.html"', html)
        self.assertIn("Manage API access", html)
        self.assertIn("sb.auth.signUp", js)
        self.assertIn("emailRedirectTo: `${window.location.origin}/analytics.html`", js)

    def test_public_status_page_uses_edge_health_and_pricing(self):
        html = self.read_public("status.html")
        js = self.read_public("status.js")
        self.assertIn("Public edge status", html)
        self.assertIn('id="upstreams"', html)
        self.assertIn('id="plans"', html)
        self.assertIn("/edge/health", js)
        self.assertIn("/pricing", js)
        self.assertIn("https://api.sagerouter.dev", js)
        self.assertIn("api.sagerouter.dev/v1", html)

    def test_waitlist_endpoint_has_non_mutating_launch_health_check(self):
        function_js = self.read_text("web", "functions", "api", "waitlist.js")
        landing = self.read_text("web", "src", "main.jsx")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        readme = self.read_text("web", "README.md")
        deploy = self.read_text("web", "DEPLOY.md")
        self.assertIn("export async function onRequestGet", function_js)
        self.assertIn("sage-router-waitlist", function_js)
        self.assertIn("primaryTable: 'sage_router_waitlist'", function_js)
        self.assertIn("fallbackTable: 'funnel_leads'", function_js)
        self.assertIn("SAGEROUTER_TURNSTILE_SECRET_KEY", function_js)
        self.assertIn("SAGEROUTER_TURNSTILE_SITE_KEY", function_js)
        self.assertIn("https://challenges.cloudflare.com/turnstile/v0/siteverify", function_js)
        self.assertIn("turnstile_required", function_js)
        self.assertIn("turnstileReady", function_js)
        self.assertIn("sanitizedUrl", function_js)
        self.assertIn("loadTurnstileScript", landing)
        self.assertIn("turnstileToken", landing)
        self.assertIn("Complete verification first.", landing)
        self.assertIn("<WaitlistForm />", landing)
        self.assertIn("/api/waitlist", readiness)
        self.assertIn("turnstileRequired", readiness)
        self.assertIn("turnstileSiteKey", readiness)
        self.assertIn("hosted waitlist endpoint is configured", readiness)
        self.assertIn("GET /api/waitlist", readme)
        self.assertIn("SAGEROUTER_TURNSTILE_SECRET_KEY", deploy)
        self.assertIn("SAGEROUTER_TURNSTILE_SITE_KEY", deploy)

    def test_openrouter_comparison_page_is_discoverable(self):
        page = self.read_text("web", "public", "compare", "openrouter.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        landing = self.read_text("web", "src", "main.jsx")
        self.assertIn("Sage Router vs OpenRouter", page)
        self.assertIn('href="https://sagerouter.dev/compare/openrouter"', page)
        self.assertIn("Create hosted API key", page)
        self.assertIn("Bring your own authorized provider access", landing)
        self.assertIn("/compare/openrouter", landing)
        self.assertIn("https://sagerouter.dev/compare/openrouter", sitemap)
        self.assertIn("OpenRouter comparison: https://sagerouter.dev/compare/openrouter", llms)
        self.assertIn("OpenRouter alternative for agents", llms_full)
        self.assertIn("SAGEROUTER_MARKETING_BASE_URL", readiness)
        self.assertIn("marketing OpenRouter comparison page is live and in sitemap", readiness)

    def test_hosted_pricing_page_and_10k_mrr_plan_are_discoverable(self):
        page = self.read_public("pricing.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")
        landing = self.read_text("web", "src", "main.jsx")
        readme = self.read_text("README.md")

        self.assertIn("Sage Router Hosted Pricing", page)
        self.assertIn("100 Lite, 200 Pro, and 50 Max customers is $10,200 MRR", page)
        self.assertIn("It does not grant unauthorized model access", page)
        self.assertIn("Managed provider access is not active in the public plans yet", page)
        self.assertIn("managedProviderAccess", page)
        self.assertIn("/provider-resale-terms", page)
        self.assertIn("/margin-policy", page)
        self.assertIn("https://sagerouter.dev/pricing", sitemap)
        self.assertIn("Hosted pricing: https://sagerouter.dev/pricing", llms)
        self.assertIn("Managed provider access is not active in public plans", llms)
        self.assertIn("balanced path to $10k MRR", llms_full)
        self.assertIn("publicLaunch.managedProviderAccess", llms_full)
        self.assertIn("/pricing", landing)
        self.assertIn("endpoint, limit, and launch metadata", readiness)
        self.assertIn("check_managed_provider_access_guard", readiness)
        self.assertIn("managed provider access remains disabled until provider resale terms", readiness)
        self.assertIn("SAGEROUTER_MANAGED_PROVIDER_RESALE_ENABLED", readiness)
        self.assertIn("marketing hosted pricing page is live and in sitemap", readiness)
        self.assertIn("Target: `$10,000 MRR`", launch_plan)
        self.assertIn("publicLaunch.managedProviderAccess", launch_plan)
        self.assertIn("margin-policy URLs", launch_plan)
        self.assertIn("docs/saas-launch-10k-mrr.md", readme)
        self.assertIn("managed provider access guard", readme)

    def test_acceptable_use_covers_managed_provider_access(self):
        page = self.read_public("acceptable-use.html")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")

        self.assertIn("Managed Provider Access", page)
        self.assertIn("provider access Sage Router is authorized to sell or operate", page)
        self.assertIn("managed-access acceptable-use boundary", readiness)

    def test_managed_provider_prerequisite_pages_are_discoverable(self):
        provider_page = self.read_public("provider-resale-terms.html")
        margin_page = self.read_public("margin-policy.html")
        pricing_page = self.read_public("pricing.html")
        sitemap = self.read_public("sitemap.xml")
        llms = self.read_public("llms.txt")
        llms_full = self.read_public("llms-full.txt")
        readiness = self.read_text("scripts", "check_sagerouter_launch_readiness.sh")
        launch_plan = self.read_text("docs", "saas-launch-10k-mrr.md")
        readme = self.read_text("README.md")

        self.assertIn("Sage Router Provider Resale Terms", provider_page)
        self.assertIn("authorized to resell or operate", provider_page)
        self.assertIn("does not authorize pooled accounts", provider_page)
        self.assertIn("Managed provider access is not active", provider_page)
        self.assertIn("Sage Router Managed Access Margin Policy", margin_page)
        self.assertIn("positive unit economics", margin_page)
        self.assertIn("not unlimited unmetered resale", margin_page)
        self.assertIn("/provider-resale-terms", pricing_page)
        self.assertIn("/margin-policy", pricing_page)
        self.assertIn("https://sagerouter.dev/provider-resale-terms", sitemap)
        self.assertIn("https://sagerouter.dev/margin-policy", sitemap)
        self.assertIn("Provider Resale Terms: https://sagerouter.dev/provider-resale-terms", llms)
        self.assertIn("Managed Access Margin Policy: https://sagerouter.dev/margin-policy", llms)
        self.assertIn("publishing those pages does not activate managed resale", llms_full)
        self.assertIn("check_managed_provider_prerequisite_pages", readiness)
        self.assertIn("marketing provider resale terms and margin policy pages are live and in sitemap", readiness)
        self.assertIn("/provider-resale-terms", launch_plan)
        self.assertIn("/margin-policy", launch_plan)
        self.assertIn("provider-resale terms and margin-policy prerequisite pages", readme)

    def test_public_deploy_helper_pins_pages_production_and_cloud_run_digest(self):
        script = self.read_text("scripts", "deploy_sagerouter_public.sh")
        readme = self.read_text("README.md")
        deploy = self.read_text("web", "DEPLOY.md")
        gcp = self.read_text("deploy", "gcp", "README.md")

        self.assertIn("SAGEROUTER_CLOUDFLARE_PAGES_PRODUCTION_BRANCH:-main", script)
        self.assertIn("mktemp -d /tmp/sage-router-web", script)
        self.assertIn("--exclude='./node_modules'", script)
        self.assertIn("pages deploy \"$tmp/dist\"", script)
        self.assertIn("npx wrangler \"${wrangler_args[@]}\"", script)
        self.assertIn("--branch \"$PAGES_PRODUCTION_BRANCH\"", script)
        self.assertIn("GHCR_IMAGE_DIGEST", script)
        self.assertIn("containerimage.digest", script)
        self.assertIn("check_sagerouter_launch_readiness.sh", script)
        self.assertIn("deploys project `sage-router-web` to production branch `main`", readme)
        self.assertIn("`master` branch with Wrangler creates a preview deployment only", deploy)
        self.assertIn("resolves the latest successful GitHub Actions `Release image` digest", gcp)


if __name__ == "__main__":
    unittest.main()
